[package]
name = "rbtek/pbtsr"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"
charm = "littensy/charm@0.10.0"